---
# This playbook installs and enables IIS on Windows hosts

- name: Install IIS
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "{{ item }}"
        state: present
        restart: yes
      with_items:
        - Web-WebServer
        - Web-Static-Content
        - Web-Http-Errors
        - Web-Http-Logging
        - Web-Asp-Net45
